-- ITEM_MASTER: 모든 아이템 기본 스펙
CREATE TABLE IF NOT EXISTS ITEM_MASTER (
  item_id     INTEGER PRIMARY KEY,
  code        TEXT    NOT NULL UNIQUE,
  name        TEXT    NOT NULL,
  description TEXT    NOT NULL DEFAULT '',
  category    TEXT    NOT NULL,
  sub_type    TEXT    NOT NULL DEFAULT '',
  req_lv      INTEGER NOT NULL DEFAULT 0,
  sell_price  INTEGER NOT NULL DEFAULT 0,
  max_stack   INTEGER NOT NULL DEFAULT 1,
  body_color  INTEGER NOT NULL DEFAULT 0,
  gem_color   INTEGER NOT NULL DEFAULT 0,
  base_atk    INTEGER NOT NULL DEFAULT 0,
  base_str    INTEGER NOT NULL DEFAULT 0,
  base_dex    INTEGER NOT NULL DEFAULT 0,
  base_int    INTEGER NOT NULL DEFAULT 0,
  base_luk    INTEGER NOT NULL DEFAULT 0,
  base_def    INTEGER NOT NULL DEFAULT 0,
  max_upgrade INTEGER NOT NULL DEFAULT 0,
  hp_recover  INTEGER NOT NULL DEFAULT 0,
  mp_recover  INTEGER NOT NULL DEFAULT 0
);

-- USER_INVENTORY: 유저 보유 아이템
CREATE TABLE IF NOT EXISTS USER_INVENTORY (
  inv_id    INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id   TEXT    NOT NULL DEFAULT 'local',
  item_id   INTEGER NOT NULL REFERENCES ITEM_MASTER(item_id),
  slot      INTEGER NOT NULL DEFAULT -1,
  quantity  INTEGER NOT NULL DEFAULT 1,
  equipped  INTEGER NOT NULL DEFAULT 0
);

-- EQUIP_INSTANCE: 장비 고유 랜덤 옵션 (USER_INVENTORY와 1:1)
CREATE TABLE IF NOT EXISTS EQUIP_INSTANCE (
  equip_id       INTEGER PRIMARY KEY AUTOINCREMENT,
  inv_id         INTEGER NOT NULL UNIQUE REFERENCES USER_INVENTORY(inv_id),
  str_bonus      INTEGER NOT NULL DEFAULT 0,
  dex_bonus      INTEGER NOT NULL DEFAULT 0,
  int_bonus      INTEGER NOT NULL DEFAULT 0,
  luk_bonus      INTEGER NOT NULL DEFAULT 0,
  atk_bonus      INTEGER NOT NULL DEFAULT 0,
  def_bonus      INTEGER NOT NULL DEFAULT 0,
  upgrade_count  INTEGER NOT NULL DEFAULT 0,
  upgrade_slots  INTEGER NOT NULL DEFAULT 0
);
